#!/usr/bin/env bash
export AYA_OUTDIR="../public"
export AYA=aya

echo "Generating RSS feed"

echo '<?xml version="1.0" encoding="utf-8"?>' > $AYA_OUTDIR/blog/rss.xml
echo '<rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:atom="http://www.w3.org/2005/Atom">' >> $AYA_OUTDIR/blog/rss.xml
echo '<channel>' >> $AYA_OUTDIR/blog/rss.xml
echo "<title>benjae's blog attempt</title>" >> $AYA_OUTDIR/blog/rss.xml
echo '<link>https://benjae.nekoweb.org/blog</link>' >> $AYA_OUTDIR/blog/rss.xml
echo "<description>Will I ever shut up?? let's see</description>" >> $AYA_OUTDIR/blog/rss.xml

for f in ./blog/*/*.md ; do
    d=$($AYA var $f date)
    if [ ! -z $d ] ; then
        timestamp=`date --date "$d" +%s`
        url=`$AYA var $f url`
        title=`$AYA var $f title | tr A-Z a-z`
        descr=`$AYA var $f description`
        echo $timestamp "<item><title>$title</title><link>https://benjae.nekoweb.org/blog/$url</link> \
                <description>$descr</description><pubDate>$(date --date @$timestamp -R)</pubDate> \
                <guid>https://benjae.nekoweb.org/blog/$url</guid></item>"
    fi
done | sort -r -n | cut -d' ' -f2- >> $AYA_OUTDIR/blog/rss.xml
echo '</channel>' >> $AYA_OUTDIR/blog/rss.xml
echo '</rss>' >> $AYA_OUTDIR/blog/rss.xml